# Creates the image for the ionic project
FROM node:18-alpine as build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install -g ionic
RUN npm install

# Copy the rest of the files
COPY . .

# Build the project
RUN ionic build --prod

# Creates the image for the nginx server
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

# Copy the build files to the nginx server
COPY --from=build /app/www /usr/share/nginx/html
